### ISSUE TITLE
BUG - Doublons sur les cours FHES

### ISSUE THREAD

**Issue by Elwan-51** [Spiti-gaming/Pycalendar#20]
Les cours FHES sont présent plusieurs fois avec un décalage de 2h.

![image](https://github.com/user-attachments/assets/99a434b9-ca18-44bf-89f1-4ea2db6d1002)

La bonne heure est présent sur le calendrier CPE et la données (salles) est présente sur le calendrier ITII.

Ils faut fusionner les deux champs, où supprimer ajuster la ligne des horaires ITII. 

Le bug semble seulement présent sur certain calendrier. Il faut potentiellement uniformiser les fuseaux horaires afin de régler le problème.

**Comment by Elwan-51** [comment]
![image](https://github.com/user-attachments/assets/61eff5fe-59de-4b0e-9af0-5615f2b31734)
Ne pas regarder les horaires (hors France en ce moment)

**Comment by Elwan-51** [comment]
![image](https://github.com/user-attachments/assets/a4cfb985-43dd-4d0f-870e-d5d5acdcef34)
Fix validé

**Comment by mlapet** [comment]
no reproduce in master
