### ISSUE TITLE
Cours not managed properly

### ISSUE THREAD

**Issue by Elwan-51** [Spiti-gaming/Pycalendar#5]
Cours are manage like personnal event and no class are assigned to them. 
<img width="74" alt="image" src="https://github.com/Spiti-gaming/Pycalendar/assets/78788340/f2385850-5191-4b81-91b1-d6451bfa1df4">

**Comment by mlapet** [comment]
Cours have two different string value :
- One with space at end
- Second without

I think, we need to delete space on event to unified all event (that can appear for other event)
